### ISSUE TITLE
Harmony UnpatchAll

### ISSUE THREAD

**Issue by rithik-b** [hardcpp/BSIndexHapticFix#1]
https://github.com/hardcpp/BSIndexHapticFix/blob/b9a840b55eb1fb87089a87ce6432c147b0cb7e87/BSIndexHapticFix/Plugin.cs#L92

Please refrain from using harmony unpatchall, instead unpatch with your harmony id. Using unpatch all can cause issues with other mod’s patches as it unpatches every mod’s patches.

**Comment by hardcpp** [comment]
Fixed on latest release.
thanks
